- package-lock.json
- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.styles.ts
> Ajuste de componente PopUp

- src/components/Login/components/GetCode/GetCode.styles.ts
- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.styles.ts
- src/components/Modal/types.ts
- src/components/SelectLoginMethod/SelectLoginMethod.styled.ts
- src/components/SelectLoginMethod/SelectLoginMethod.tsx
- src/ui/ui-landing-header/ui-landing-header.styled.ts
- src/ui/ui-landing-header/ui-landing-header.tsx
> [SU-5053]-mejoras Login

- src/components/SelectLoginMethod/SelectLoginMethod.styled.ts
- src/ui/ui-landing-header/ui-landing-header.styled.ts
> [SU-5373]-errores Login

- src/components/Login/components/LoginContainer/LoginContainer.styles.ts
> [SU-5568]-ajustes login

- src/styles/icons.css
- src/ui/ui-icons/ui-icons.stories.mdx
> [SU-5649]-iconos

- src/components/Login/Login.tsx
- src/components/Login/index.ts
- src/components/Login/types.ts
> fix login type

- src/styles/icons.css
- src/ui/ui-icons/ui-icons.stories.mdx
ajuste de iconos no documentados y subida de otros
> [SU-6678] ajustes de iconos

- src/components/Login/components/GetCode/GetCode.styles.ts
- src/components/Login/components/GetCode/GetCode.tsx
- src/components/Login/components/GetCodeByEmail/GetCodeByEmail.tsx
> [SU-5955]-ajustes login

- src/components/DownloadAppButton/DownloadAppButton.styled.ts
- src/components/DownloadAppButton/DownloadAppButton.tsx
- src/components/Login/Login.tsx
- src/components/Login/components/RegisterInApp/RegisterInApp.styled.ts
- src/components/Login/components/RegisterInApp/RegisterInApp.tsx
> ajustes register in App

- src/components/Login/components/RegisterInApp/RegisterInApp.styled.ts
> [SU-5955]-ajuste login

- src/components/Login/types.ts
[1] - agregando payload en logEvent
> [SU-7185] agregando payload en logEvent

- src/common/consts/events.ts
- src/components/Login/Login.tsx
- src/components/Login/components/ValidateCode/ValidateCode.tsx
- src/components/SelectLoginMethod/SelectLoginMethod.tsx
- src/styles/icons.css
- src/ui/ui-icons/ui-icons.stories.mdx
- Ajustes evento source metodo de login
> ajustes evento source metodo de login

- src/styles/icons.css
- src/ui/ui-icons/ui-icons.stories.mdx
> iconos nuevos dec

- src/components/Login/Login.tsx
- ajuste evento login con teléfono
> ajuste evento login con teléfono

- src/styles/icons.css
- src/ui/ui-icons/ui-icons.stories.mdx
- nuevos iconos del footer en ecommerce
> SU-7406 nuevos iconos del footer en ecommerce

- src/styles/icons.css
- src/ui/ui-icons/ui-icons.stories.mdx
> Nuevo icono go up

- src/ui/ui-landing-header/ui-landing-header.tsx
> [SU-8084]ajuste menu header

- src/styles/icons.css
- src/ui/ui-icons/ui-icons.stories.mdx
> nuevo icon chart

- src/styles/icons.css
- src/ui/ui-icons/ui-icons.stories.mdx
- Nuevos iconos para pagina interna de producto
> Nuevos iconos para pagina interna de producto

- .storybook/preview.js
- src/components/Modal/Modal.styles.ts
- eliminar color que genera problema en modal
> eliminar color que genera problema en modal

- src/styles/icons.css
- src/ui/ui-icons/ui-icons.stories.mdx
> nuevos iconos feb 28

- src/styles/icons.css
- src/ui/ui-icons/ui-icons.stories.mdx
> nuevo icon menu 

- src/ui/ui-landing-header/ui-landing-header.tsx
> borrar item del menu

- src/ui/ui-landing-header/ui-landing-header.tsx
- ajuste texto en el menu header
> [SU-10038] ajuste texto en el menu header
